{% set version = "1.7.0" %}

package:
  name: rdfind
  version: {{ version }}

source:
  url: https://github.com/pauldreik/rdfind/archive/releases/{{ version }}.tar.gz
  sha256: bd17dbd9c6c9fc0c0b016b3e77ecf5cd718eee428172c767f429ba30405816d8

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - automake
    - autoconf-archive
    # Need for GNU readlink in PATH
    - coreutils
    - make
  host:
    - nettle
    - xxhash

test:
  commands:
    - rdfind --version
    - rdfind --help
    - rdfind -checksum xxh128 .

about:
  home: https://rdfind.pauldreik.se
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Rdfind is a program that finds duplicate files. It is useful for compressing backup directories or just finding duplicate files. It compares files based on their content, NOT on their file names.
  dev_url: https://github.com/pauldreik/rdfind
  doc_url: https://rdfind.pauldreik.se/rdfind.1.html

extra:
  recipe-maintainers:
    - nehaljwani
